In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


<h1><u>Iteración 3</u> : Programación numérica, dataframes y análisis estadístico </h1> 

- En esta tarea trabajarás con la librería numpy y con los datos de la librería sklearn.datasets. De esta librería descarga el conjunto de datos denominado Iris.

<h2>Ejercicio 1</h2>
<b><u>Instrucción</u></b> Cargar "data" y "target" del conjunto de datos, y visualiza los 10 primeros registros de cada uno.

In [2]:
from sklearn.datasets import load_iris
import numpy as np
iris=load_iris();
data=iris.data
target=iris.target[:,np.newaxis]
print("A continuación mostramos las primeras \n10 observaciones del dataset 'data' \n"+ str(data[:10])+"\n\n")

print("Seguido de las primeras observaciones del dataset 'target' \n"+str(target[:10]))

A continuación mostramos las primeras 
10 observaciones del dataset 'data' 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


Seguido de las primeras observaciones del dataset 'target' 
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

<h2>Ejercicio 2</h2>
<b><u>Instrucción</u></b> Concatena “data” y “target” en un nuevo array. Muestra los 5 primeros registros.

In [4]:
conjunto_e2 = np.concatenate((data,target),axis=1)
print(conjunto_e2[:5])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


<h2>Ejercicio 3</h2>
<b><u>Instrucción</u></b> Calcula la media y desviación estándar de la longitud del sépalo ("sepal length (cm)") y la longitud del pétalo ("petal length (cm)"). Muestra los resultados con dos decimales.

In [5]:
print("La media de la longitud del sépalo es de "+str(data[:,0].mean().round(2)) +" cm y la desviación estándar "+str(data[:,0].std().round(2))+" cm.\n\n")
print("La media de la longitud del pétalo es de "+str(data[:,2].mean().round(2)) +" cm y la desviación estándar "+str(data[:,2].std().round(2))+" cm.")

La media de la longitud del sépalo es de 5.84 cm y la desviación estándar 0.83 cm.


La media de la longitud del pétalo es de 3.76 cm y la desviación estándar 1.76 cm.


<h2>Ejercicio 4</h2>
<b><u>Instrucción</u></b> Selecciona una muestra aleatoria de 20 registros del conjunto obtenido en el ejercicio anterior.

In [6]:
np.random.seed(110693)
indices= np.random.randint(0,149,20)
conjunto_e2[indices]

array([[5. , 3.5, 1.3, 0.3, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [6.7, 3. , 5.2, 2.3, 2. ],
       [7.3, 2.9, 6.3, 1.8, 2. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [6.9, 3.1, 5.1, 2.3, 2. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [6.4, 3.1, 5.5, 1.8, 2. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [5. , 2.3, 3.3, 1. , 1. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [5.4, 3.9, 1.7, 0.4, 0. ]])

<h2>Ejercicio 5</h2>
<b><u>Instrucción</u></b> Crea una matriz que muestre: 

- La media de cada característica por especie.
- La desviación estándar de cada característica por especie.

In [7]:
# Aqui creamos un array varío para llenar los doce espacios con la información de las medias por característica por especie.
mean_matriz=np.empty((3,4))
# A continuación creamos un array de los códigos únicos que tenemos para identificar las distintas especies. 
# En este caso son 3 distintas especies.
arr_spec_1=np.unique(conjunto_e2[:,4])
# Nos aseguramos de que los elementos de nuestro array sean integers para poder iterar sobre estos elementos y utilizarlos como índices. 
arr_spec=np.asarray(arr_spec_1,dtype='int')
# Convertimos el array en una lista para poder iterar.
arr=arr_spec.tolist()
# Iniciamos con el for para rellenar la matriz de media por especie y característica.
for n in arr:
    mean_matriz[n]=conjunto_e2[(50*n):(50*(n+1))].mean(0)[:4]

print("La matriz de medias de características por especie es la siguiente \n"+str(mean_matriz)+"\n\n")
# Aquí creamos la matriz vacía que utilizamos para la desviación estandar por especie y característica.
std_matriz=np.empty((3,4))
for m in arr:
    std_matriz[m]=conjunto_e2[(50*m):(50*(m+1))].std(0)[:4]
print("La matriz de desviación estandar de características por especie es la siguiente: \n"+str(std_matriz))


La matriz de medias de características por especie es la siguiente 
[[5.006 3.428 1.462 0.246]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]


La matriz de desviación estandar de características por especie es la siguiente: 
[[0.34894699 0.37525458 0.17191859 0.10432641]
 [0.51098337 0.31064449 0.46518813 0.19576517]
 [0.62948868 0.31925538 0.54634787 0.27188968]]


<h2>Ejercicio 6</h2>
<b><u>Instrucciones</u></b></n> 

- Calcula la cantidad de muestras por especie.

In [8]:
# Para iniciar el conteo, declaramos las siguientes 3 variables con valor 0, 
# y conformque iteremos en los elementos de la muestra completa iremos catalogando 
# observaciones según la especie.
set=0
versi=0
virg=0
for n in conjunto_e2[:,4].tolist():
    if n==0:
        set+=1
    elif n==1:
        versi+=1
    else:
        virg+=1
print("En la muestra, existen "+str(set)+" observaciones para la especie Setosa, \n"+str(versi)+" observaciones de la especie versicolor, y "+str(virg)+" observaciones de la especie virginica.")

En la muestra, existen 50 observaciones para la especie Setosa, 
50 observaciones de la especie versicolor, y 50 observaciones de la especie virginica.


- Encuentra la especie con el valor máximo promedio de la variable "sepal length (cm)"

In [15]:
# Para resolver este ejercicio podemos observar la matriz de medias por característica y especia del ejercicio 5.
# max_val=max(mean_matriz[:,0])
# Este primer loop sirve para identificar el valor máximo promedio de la variabe 'sepal lenght (cm)'
for i in np.arange(len(iris.feature_names)):
    if iris.feature_names[i]=='sepal length (cm)':
        max_val=max(mean_matriz[:,i])
        k=i
print("El valor máximo promedio de la variable 'sepal lenght (cm)' es: "+ str(round(max_val,2))+"\n ")
# Y con este segundo loop identificamos el renglón en el que se encuentra dicho valor y extraemos el nombre de la especie de la tabla correspondiente
for j in np.arange(len(iris.target_names)):
    if mean_matriz[j,k]==max_val:
        sg=iris.target_names[j]
print("La especie con el valor máximo promedio de la variable 'sepal lenght (cm)' es: "+sg)

El valor máximo promedio de la variable 'sepal lenght (cm)' es: 6.59
 
La especie con el valor máximo promedio de la variable 'sepal lenght (cm)' es: virginica


<h2>Ejercicio 7</h2>
<b><u>Instrucciones</u></b> 

- Calcula la matrix de correlación entre variables.
- Filtra los valores mayores a la media de la longitud de los pétalos y muéstralo.
- Encuentra la muestra con los pétalos más grandes.

In [ ]:
# Matriz de correlación entre variables.
print(np.corrcoef(np.transpose(data)))

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


In [ ]:
# Filtraremos las observaciones con valores mayores al promedio de la longitud de los pétalos.
promedio=conjunto_e2.mean(0)[2]
print(promedio)
print("La siguiente matriz contiene las observaciones de flores con una longitud de pétalos mayor al promedio"+str(conjunto_e2[conjunto_e2[:,2]>promedio]))

3.7580000000000027
La siguiente matriz contiene las observaciones de flores con una longitud de pétalos mayor al promedio[[7.  3.2 4.7 1.4 1. ]
 [6.4 3.2 4.5 1.5 1. ]
 [6.9 3.1 4.9 1.5 1. ]
 [5.5 2.3 4.  1.3 1. ]
 [6.5 2.8 4.6 1.5 1. ]
 [5.7 2.8 4.5 1.3 1. ]
 [6.3 3.3 4.7 1.6 1. ]
 [6.6 2.9 4.6 1.3 1. ]
 [5.2 2.7 3.9 1.4 1. ]
 [5.9 3.  4.2 1.5 1. ]
 [6.  2.2 4.  1.  1. ]
 [6.1 2.9 4.7 1.4 1. ]
 [6.7 3.1 4.4 1.4 1. ]
 [5.6 3.  4.5 1.5 1. ]
 [5.8 2.7 4.1 1.  1. ]
 [6.2 2.2 4.5 1.5 1. ]
 [5.6 2.5 3.9 1.1 1. ]
 [5.9 3.2 4.8 1.8 1. ]
 [6.1 2.8 4.  1.3 1. ]
 [6.3 2.5 4.9 1.5 1. ]
 [6.1 2.8 4.7 1.2 1. ]
 [6.4 2.9 4.3 1.3 1. ]
 [6.6 3.  4.4 1.4 1. ]
 [6.8 2.8 4.8 1.4 1. ]
 [6.7 3.  5.  1.7 1. ]
 [6.  2.9 4.5 1.5 1. ]
 [5.5 2.4 3.8 1.1 1. ]
 [5.8 2.7 3.9 1.2 1. ]
 [6.  2.7 5.1 1.6 1. ]
 [5.4 3.  4.5 1.5 1. ]
 [6.  3.4 4.5 1.6 1. ]
 [6.7 3.1 4.7 1.5 1. ]
 [6.3 2.3 4.4 1.3 1. ]
 [5.6 3.  4.1 1.3 1. ]
 [5.5 2.5 4.  1.3 1. ]
 [5.5 2.6 4.4 1.2 1. ]
 [6.1 3.  4.6 1.4 1. ]
 [5.8 2.6 4.  1.2 1. ]
 [5.6

<h2>Ejercicio 8</h2>
<b><u>Instrucción</u></b> 

- Halla la especie con la mayor diferencia entre la longitud media de sépalos y pétalos.

In [ ]:
# Para resolver este ejercicio usaremos la matriz creada en el ejercicio 5 
# para comparar medias directamente y ubicar a la especie que cumpla con lo que buscamos.

# En la variable winner almacenamos un array con la diferencia entre el largo promedio de los petalos y los sépalos por especie.
winner=mean_matriz[:,0]-mean_matriz[:,2]
w=0
maxi=max(winner)
for n in np.arange(len(winner)):
    if winner[n]==maxi:
        w=n
    else:
        print("La especie "+iris.target_names[n]+" no es la que buscas, \ny por cierto la diferencia entre su longitud promedio de pétalos y sépalos es de "+str(round(winner[n],2))+"\n")

print("La especie que presenta mayor diferencia entre la longitud promedio de sus pétalos y sépalos es: " +iris.target_names[w])
# np.nonzero(max(mean_matriz[:,0]-mean_matriz[:,2])==abs(mean_matriz[:,0]-mean_matriz[:,2]))

La especie versicolor no es la que buscas, 
y por cierto la diferencia entre su longitud promedio de pétalos y sépalos es de 1.68

La especie virginica no es la que buscas, 
y por cierto la diferencia entre su longitud promedio de pétalos y sépalos es de 1.04

La especie que presenta mayor diferencia entre la longitud promedio de sus pétalos y sépalos es: setosa
